import { useState, useEffect, useCallback } from 'react';
import { Task } from '@/features/profile/domain/Task';
import { GetUserTasksUseCase } from '@/features/profile/application/GetUserTasksUseCase';
import { CreateTaskUseCase } from '@/features/profile/application/CreateTaskUseCase';
import { FirebaseTaskRepository } from '@/features/profile/infrastructure/FirebaseTaskRepository';

/**
 * Hook to fetch and manage tasks.
 * @param userId The ID of the user to fetch tasks for.
 * @returns Tasks, loading state, error state, and a function to create a task.
 */
export const useTasks = (userId: string | undefined) => {
    const [tasks, setTasks] = useState<Task[]>([]);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    const taskRepo = new FirebaseTaskRepository();
    const getUserTasksUseCase = new GetUserTasksUseCase(taskRepo);
    const createTaskUseCase = new CreateTaskUseCase(taskRepo);

    const fetchTasks = useCallback(async () => {
        if (!userId) return;
        setLoading(true);
        try {
            const fetchedTasks = await getUserTasksUseCase.execute(userId);
            setTasks(fetchedTasks);
        } catch (err) {
            setError('Failed to load tasks');
            console.error(err);
        } finally {
            setLoading(false);
        }
    }, [userId]);

    useEffect(() => {
        if (userId) {
            fetchTasks();
        } else {
            setLoading(false);
        }
    }, [userId, fetchTasks]);

    const createTask = async (title: string, description: string, date: Date) => {
        if (!userId) return;
        try {
            const newTask: Task = {
                id: '', // Generated by Firestore
                title,
                description,
                date,
                userId,
                createdAt: new Date(),
            };
            await createTaskUseCase.execute(newTask);
            await fetchTasks(); // Refresh list
        } catch (err) {
            setError('Failed to create task');
            console.error(err);
            throw err;
        }
    };

    return { tasks, loading, error, createTask };
};
